### ISSUE TITLE
possibility to allow voices to be used outside of TnH

### ISSUE THREAD

**Issue by Rin-Rem** [potatoes1286/TNH-BGMLoader#21]
it was like this awhile ago, where voicelines i had downloaded and used in TnH would be working outside of TnH. was wondering if there was a way to enable this or add the ability to do this again sometime in the future. i miss being able to hear custom voicelines while not playing TnH. not asking for anything other then voicelines. the voices would be the only thing i request outside of TnH.

**Comment by potatoes1286** [comment]
I wasn't aware that it worked before, or stopped working. Will look into this, thanks

**Comment by Colboto** [comment]
Just tossing a comment onto this. This actually does work today for me, you just have to go into TnH's menu system and select the voicelines you want first, then leave TnH and the voicelines stick until you quit the game. So for me it's technically implemented, I just add an extra step of hopping into the TnH lobby, pick a voice, leave for a different mode.

**Comment by Rin-Rem** [comment]
> Just tossing a comment onto this. This actually does work today for me, you just have to go into TnH's menu system and select the voicelines you want first, then leave TnH and the voicelines stick until you quit the game. So for me it's technically implemented, I just add an extra step of hopping into the TnH lobby, pick a voice, leave for a different mode.

im a little late in this reply, im sorry about that, but i wanted to come by and say this is how i got it to work before. but for some reason it stopped working for me, all voices stay default in any mode i try. it used to work with every mode that had sosigs, even modded modes. but now it doesnt work at all unless im in tnh.

**Comment by Rin-Rem** [comment]
it was corrupted and had old files, i fixed the issue. ui is still a bit bugged, but it remains visual only. closing this thread <3
